#!/usr/bin/env python3
"""Recover the current V4 source trajectories from semantic evidence packets.

This command reads the public GSM8K dataset but never creates a network API
client or reads a paid-provider credential.  It writes a new recovery lineage;
it does not recreate or overwrite the lost Phase-1 directory.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import shlex
import sys
from typing import Any, Iterable, Mapping


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from memgen.experience.phase1 import create_gsm8k_split_manifest, file_sha256
from memgen.experience.v4_question_recovery import (
    V4_QUESTION_RECOVERY_EXPECTED_BANKS,
    V4_QUESTION_RECOVERY_EXPECTED_EVIDENCE,
    build_question_recovery_manifest,
    build_recovered_source_records,
    validate_question_recovery_manifest,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--recovery-id", required=True)
    parser.add_argument("--semantic-evidence-packets", type=Path, required=True)
    parser.add_argument("--bank-records", type=Path, required=True)
    parser.add_argument("--bank-manifest", type=Path, required=True)
    parser.add_argument("--side-kv-manifest", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--dataset-revision", default="main")
    parser.add_argument("--bank-source-size", type=int, default=6000)
    parser.add_argument("--calibration-val-size", type=int, default=1000)
    parser.add_argument("--split-seed", type=int, default=42)
    parser.add_argument("--resume", action="store_true")
    return parser.parse_args()


def _write_json(path: Path, value: Mapping[str, Any]) -> None:
    temporary = path.with_name(f".{path.name}.tmp")
    with temporary.open("w", encoding="utf-8") as handle:
        json.dump(value, handle, ensure_ascii=False, indent=2, sort_keys=True)
        handle.write("\n")
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(temporary, path)


def _write_jsonl(path: Path, rows: Iterable[Mapping[str, Any]]) -> int:
    temporary = path.with_name(f".{path.name}.tmp")
    count = 0
    with temporary.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n")
            count += 1
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(temporary, path)
    return count


def _write_environment(path: Path) -> None:
    root = path.parent.resolve()
    content = "\n".join(
        (
            "# Generated by recover_v4_source_evidence.py; contains no credentials.",
            f"export MEMGEN_V4_RECOVERY_DIR={shlex.quote(str(root))}",
            "export MEMGEN_V4_RECOVERY_MANIFEST="
            + shlex.quote(str(root / "v4_question_recovery_manifest.json")),
            "export MEMGEN_V4_RECOVERED_EXPERIENCES="
            + shlex.quote(str(root / "recovered_source_experiences.jsonl")),
            "export MEMGEN_V4_RECOVERED_SPLIT_MANIFEST="
            + shlex.quote(str(root / "split_manifest.json")),
            "",
        )
    )
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(content, encoding="utf-8")
    os.replace(temporary, path)


def main() -> None:
    args = parse_args()
    source_paths = (
        args.semantic_evidence_packets,
        args.bank_records,
        args.bank_manifest,
        args.side_kv_manifest,
    )
    for path in source_paths:
        if not path.is_file() or path.stat().st_size == 0:
            raise FileNotFoundError(path)
    output_dir = args.output_dir.expanduser().resolve()
    manifest_path = output_dir / "v4_question_recovery_manifest.json"
    split_path = output_dir / "split_manifest.json"
    experiences_path = output_dir / "recovered_source_experiences.jsonl"
    environment_path = output_dir / "USE_THIS_RECOVERY.env"
    if manifest_path.is_file():
        if not args.resume:
            raise ValueError("Recovery output is sealed; pass --resume to authenticate it")
        manifest = validate_question_recovery_manifest(manifest_path)
        if manifest.get("recovery_id") != args.recovery_id:
            raise ValueError("Recovery output belongs to another recovery ID")
        passed_bindings = (
            (args.semantic_evidence_packets, "semantic_evidence_packets"),
            (args.bank_records, "curated_bank_records"),
            (args.bank_manifest, "curated_bank_manifest"),
            (args.side_kv_manifest, "side_kv_manifest"),
        )
        if any(
            manifest["sources"][name]["sha256"] != file_sha256(path)
            for path, name in passed_bindings
        ):
            raise ValueError("Recovery resume inputs differ from the sealed lineage")
        print(
            f"[v4-question-recovery] reuse id={args.recovery_id} "
            f"evidence={manifest['counts']['evidence_count']} manifest={manifest_path}",
            flush=True,
        )
        return
    if output_dir.exists() and any(output_dir.iterdir()):
        raise ValueError("Recovery output directory is non-empty but not sealed")
    output_dir.mkdir(parents=True, exist_ok=True)

    try:
        from datasets import load_dataset
    except ImportError as exc:
        raise RuntimeError("datasets is required; install requirements.txt first") from exc
    dataset = load_dataset(
        "openai/gsm8k", "main", revision=args.dataset_revision
    )
    split_manifest = create_gsm8k_split_manifest(
        dataset["train"],
        dataset["test"],
        bank_source_size=args.bank_source_size,
        calibration_val_size=args.calibration_val_size,
        seed=args.split_seed,
        dataset_revision=args.dataset_revision,
        train_fingerprint=getattr(dataset["train"], "_fingerprint", None),
        test_fingerprint=getattr(dataset["test"], "_fingerprint", None),
    )
    _write_json(split_path, split_manifest)
    records, summary = build_recovered_source_records(
        semantic_packets_path=args.semantic_evidence_packets.resolve(),
        bank_records_path=args.bank_records.resolve(),
        bank_manifest_path=args.bank_manifest.resolve(),
        side_kv_manifest_path=args.side_kv_manifest.resolve(),
        split_manifest=split_manifest,
        train_records=dataset["train"],
        expected_bank_count=V4_QUESTION_RECOVERY_EXPECTED_BANKS,
        expected_evidence_count=V4_QUESTION_RECOVERY_EXPECTED_EVIDENCE,
    )
    written = _write_jsonl(experiences_path, records)
    if written != V4_QUESTION_RECOVERY_EXPECTED_EVIDENCE:
        raise RuntimeError("V4 question recovery did not write all curated evidence")
    manifest = build_question_recovery_manifest(
        recovery_id=args.recovery_id,
        semantic_packets_path=args.semantic_evidence_packets.resolve(),
        bank_records_path=args.bank_records.resolve(),
        bank_manifest_path=args.bank_manifest.resolve(),
        side_kv_manifest_path=args.side_kv_manifest.resolve(),
        split_manifest_path=split_path,
        recovered_experiences_path=experiences_path,
        summary=summary,
    )
    _write_json(manifest_path, manifest)
    _write_environment(environment_path)
    validate_question_recovery_manifest(manifest_path)
    print(
        f"[v4-question-recovery] sealed id={args.recovery_id} "
        f"banks={summary['bank_count']} evidence={written} "
        f"external_api_calls=0 manifest={manifest_path}",
        flush=True,
    )


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"[v4-question-recovery] error: {exc}", file=sys.stderr)
        raise
